//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public System.Guid deviceID { get; set; }
        public System.Guid userID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool isSensor { get; set; }
        public bool isEnabled { get; set; }
        public Nullable<double> SensorValue { get; set; }
        public string SensorType { get; set; }
    
        public virtual User User { get; set; }
    }
}
